import {
  Service,
  Project,
  Testimonial,
  TeamMember,
  ServiceArea,
} from './schema'

export const services: Service[] = [
  {
    id: 'lawn-maintenance',
    name: 'Lawn Maintenance',
    excerpt: 'Professional lawn care and maintenance services',
    description:
      'Keep your lawn looking its best year-round with our comprehensive maintenance program. Includes mowing, edging, trimming, and seasonal care.',
    icon: 'Grass',
    features: [
      'Weekly/bi-weekly mowing',
      'Edging and trimming',
      'Fertilization program',
      'Weed control',
      'Seasonal cleanup',
      'Leaf removal',
    ],
    price: 'From $45/week',
    duration: 'Weekly or bi-weekly',
    image: 'https://images.pexels.com/photos/1001676/pexels-photo-1001676.jpeg',
  },
  {
    id: 'landscape-design',
    name: 'Landscape Design',
    excerpt: 'Custom landscape design and planning',
    description:
      'Transform your outdoor space with our expert landscape design services. We create beautiful, functional designs that enhance your property value.',
    icon: 'Palette',
    features: [
      'Site analysis and planning',
      '3D design renderings',
      'Plant selection',
      'Hardscape design',
      'Irrigation planning',
      'Project management',
    ],
    price: 'From $2,500',
    duration: '2-4 weeks',
    image: 'https://images.pexels.com/photos/33404224/pexels-photo-33404224.jpeg',
  },
  {
    id: 'hardscaping',
    name: 'Hardscaping',
    excerpt: 'Patios, walkways, and retaining walls',
    description:
      'Create beautiful outdoor living spaces with our hardscaping services. From patios to retaining walls, we build structures that last.',
    icon: 'Hammer',
    features: [
      'Patio construction',
      'Walkway installation',
      'Retaining walls',
      'Outdoor kitchens',
      'Fire pits',
      'Water features',
    ],
    price: 'From $5,000',
    duration: '1-3 weeks',
    image: 'https://images.unsplash.com/photo-1596481768453-8befafc2d7ae?q=80&w=1674&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    id: 'tree-services',
    name: 'Tree Services',
    excerpt: 'Tree trimming, removal, and care',
    description:
      'Professional tree care services to keep your trees healthy and safe. From trimming to removal, we handle all your tree care needs.',
    icon: 'TreePine',
    features: [
      'Tree trimming and pruning',
      'Tree removal',
      'Stump grinding',
      'Disease treatment',
      'Emergency services',
      'Tree health assessment',
    ],
    price: 'From $150',
    duration: 'Same day to 1 week',
    image: 'https://images.pexels.com/photos/6218318/pexels-photo-6218318.jpeg',
  },
  {
    id: 'irrigation',
    name: 'Irrigation Systems',
    excerpt: 'Smart irrigation installation and repair',
    description:
      'Efficient irrigation systems that save water and keep your landscape healthy. We install, repair, and maintain all types of irrigation systems.',
    icon: 'Droplets',
    features: [
      'System design and installation',
      'Smart controller setup',
      'Drip irrigation',
      'Sprinkler repair',
      'Seasonal adjustments',
      'Water conservation',
    ],
    price: 'From $3,000',
    duration: '1-2 weeks',
    image: 'https://images.unsplash.com/photo-1630862338638-6cf93f610dd8?q=80&w=1933&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    id: 'seasonal-cleanup',
    name: 'Seasonal Cleanup',
    excerpt: 'Spring and fall landscape cleanup',
    description:
      'Prepare your landscape for each season with our comprehensive cleanup services. We handle debris removal, pruning, and preparation.',
    icon: 'Leaf',
    features: [
      'Spring cleanup',
      'Fall preparation',
      'Debris removal',
      'Garden bed preparation',
      'Mulching',
      'Plant protection',
    ],
    price: 'From $300',
    duration: '1-3 days',
    image: 'https://images.unsplash.com/photo-1733286125300-b4c5563295ad?q=80&w=1732&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
]

export const projects: Project[] = [
  {
    id: 'modern-backyard-oasis',
    title: 'Modern Backyard Oasis',
    excerpt: 'Contemporary outdoor living space with custom hardscaping',
    description:
      'A complete transformation of a suburban backyard into a modern outdoor living space. Features include a custom stone patio, outdoor kitchen, fire pit, and sophisticated landscaping.',
    cover: 'https://images.pexels.com/photos/1590336/pexels-photo-1590336.jpeg',
    images: [
      'https://images.pexels.com/photos/1590336/pexels-photo-1590336.jpeg',
      'https://images.pexels.com/photos/1001676/pexels-photo-1001676.jpeg',
      'https://images.pexels.com/photos/33404224/pexels-photo-33404224.jpeg',
    ],
    tags: ['Hardscaping', 'Outdoor Living', 'Modern Design'],
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '78701',
    date: '2024-03-15',
    services: ['landscape-design', 'hardscaping'],
    beforeImage: 'https://images.pexels.com/photos/6218318/pexels-photo-6218318.jpeg',
    afterImage: 'https://images.pexels.com/photos/1590336/pexels-photo-1590336.jpeg',
  },
  {
    id: 'drought-resistant-garden',
    title: 'Drought-Resistant Garden',
    excerpt: 'Water-wise landscaping with native plants',
    description:
      'A beautiful, low-maintenance garden designed to thrive in our local climate. Features drought-resistant native plants, efficient irrigation, and sustainable design principles.',
    cover: 'https://images.unsplash.com/photo-1655731986321-d9bee041ec88?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    images: [
      'https://images.pexels.com/photos/33404224/pexels-photo-33404224.jpeg',
      'https://images.pexels.com/photos/1001676/pexels-photo-1001676.jpeg',
    ],
    tags: ['Native Plants', 'Water Conservation', 'Low Maintenance'],
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '78702',
    date: '2024-02-20',
    services: ['landscape-design', 'irrigation'],
    beforeImage: 'https://images.pexels.com/photos/6218318/pexels-photo-6218318.jpeg',
    afterImage: 'https://images.pexels.com/photos/33404224/pexels-photo-33404224.jpeg',
  },
  {
    id: 'family-friendly-yard',
    title: 'Family-Friendly Yard',
    excerpt: 'Safe and fun outdoor space for children',
    description:
      'A family-oriented landscape design that creates a safe, engaging outdoor environment for children while maintaining aesthetic appeal for adults.',
    cover: 'https://images.unsplash.com/photo-1626075246403-544a14566c3d?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    images: [
      'https://images.pexels.com/photos/1001676/pexels-photo-1001676.jpeg',
      'https://images.pexels.com/photos/1590336/pexels-photo-1590336.jpeg',
    ],
    tags: ['Family', 'Safety', 'Play Areas'],
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '78703',
    date: '2024-01-10',
    services: ['landscape-design', 'lawn-maintenance'],
    beforeImage: 'https://images.pexels.com/photos/6218318/pexels-photo-6218318.jpeg',
    afterImage: 'https://images.pexels.com/photos/1001676/pexels-photo-1001676.jpeg',
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Jennifer Martinez',
    text: 'The team transformed our neglected backyard into a beautiful outdoor living space. They were professional, on time, and exceeded our expectations. Highly recommend!',
    rating: 5,
    city: 'Phoenix, AZ',
    date: '2024-03-20',
    project: 'Modern Backyard Oasis',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: '2',
    name: 'Robert Kim',
    text: 'Excellent service from start to finish. Our drought-resistant garden looks amazing and requires minimal maintenance. The irrigation system is smart and efficient.',
    rating: 5,
    city: 'Scottsdale, AZ',
    date: '2024-02-25',
    project: 'Drought-Resistant Garden',
    avatar: 'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: '3',
    name: 'Amanda Foster',
    text: 'Professional, reliable, and creative. They understood our vision and delivered beyond what we imagined. Our family loves spending time in our new yard.',
    rating: 5,
    city: 'Mesa, AZ',
    date: '2024-01-15',
    project: 'Family-Friendly Yard',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: '4',
    name: 'Carlos Rodriguez',
    text: 'Outstanding work on our landscape design. The team was knowledgeable about local plants and created a beautiful, sustainable garden that enhances our home.',
    rating: 5,
    city: 'Tempe, AZ',
    date: '2024-01-05',
    project: 'Custom Garden Design',
    avatar: 'https://images.pexels.com/photos/1648387/pexels-photo-1648387.jpeg?w=800&h=800&fit=crop&crop=face',
  },
  {
    id: '5',
    name: 'Sarah Williams',
    text: 'Incredible attention to detail! They created a stunning outdoor kitchen and patio area that we use year-round. The quality of workmanship is outstanding.',
    rating: 5,
    city: 'Chandler, AZ',
    date: '2024-01-10',
    project: 'Outdoor Kitchen & Patio',
    avatar: 'https://images.pexels.com/photos/1462630/pexels-photo-1462630.jpeg?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: '6',
    name: 'David Chen',
    text: 'They transformed our boring front yard into a welcoming entrance that gets compliments from all our neighbors. Professional service and beautiful results!',
    rating: 5,
    city: 'Gilbert, AZ',
    date: '2024-02-15',
    project: 'Front Yard Makeover',
    avatar: 'https://images.pexels.com/photos/3761521/pexels-photo-3761521.jpeg?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: '7',
    name: 'Lisa Thompson',
    text: 'Amazing work on our pool landscaping! They created a tropical paradise that makes us feel like we\'re on vacation every day. Highly skilled team!',
    rating: 5,
    city: 'Peoria, AZ',
    date: '2024-02-28',
    project: 'Pool Landscaping',
    avatar: 'https://images.pexels.com/photos/20335528/pexels-photo-20335528.jpeg?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: '8',
    name: 'Craig Green',
    text: 'The best landscaping company we\'ve ever worked with. They completed our project on time and budget, and the results exceeded our expectations.',
    rating: 5,
    city: 'Surprise, AZ',
    date: '2024-03-01',
    project: 'Complete Yard Renovation',
    avatar: 'https://images.pexels.com/photos/1181391/pexels-photo-1181391.jpeg?w=150&h=150&fit=crop&crop=face',
  },
]

export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Marcus Green',
    role: 'Owner & Lead Designer',
    bio: 'With over 15 years of experience in landscape design and construction, Marcus brings creativity and expertise to every project. He specializes in sustainable design and native plant selection.',
    image: '/images/team/marcus-green.jpg',
    credentials: [
      'Licensed Landscape Architect',
      'Certified Arborist',
      'Sustainable Landscape Professional',
    ],
    experience: '15+ years',
    specialties: [
      'Landscape Design',
      'Sustainable Landscaping',
      'Native Plants',
    ],
  },
  {
    id: '2',
    name: 'Lisa Martinez',
    role: 'Senior Landscape Designer',
    bio: 'Lisa combines artistic vision with technical expertise to create stunning outdoor spaces. She has a passion for creating landscapes that are both beautiful and functional.',
    image: '/images/team/lisa-martinez.jpg',
    credentials: [
      'Landscape Design Degree',
      'Certified Landscape Designer',
      'Water Conservation Specialist',
    ],
    experience: '12+ years',
    specialties: ['Residential Design', 'Water Features', 'Garden Design'],
  },
  {
    id: '3',
    name: 'James Wilson',
    role: 'Hardscape Specialist',
    bio: 'James is our expert in all things hardscaping, from patios to retaining walls. His attention to detail and craftsmanship ensures that every structure is built to last.',
    image: '/images/team/james-wilson.jpg',
    credentials: [
      'Masonry Certification',
      'Concrete Specialist',
      'Safety Certified',
    ],
    experience: '10+ years',
    specialties: ['Patio Construction', 'Retaining Walls', 'Outdoor Kitchens'],
  },
]

export const serviceAreas: ServiceArea[] = [
  {
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '78701',
    county: 'Travis',
    distance: 0,
  },
  {
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '78702',
    county: 'Travis',
    distance: 2,
  },
  {
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '78703',
    county: 'Travis',
    distance: 3,
  },
  {
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '78704',
    county: 'Travis',
    distance: 4,
  },
  {
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '78705',
    county: 'Travis',
    distance: 5,
  },
  {
    city: 'Tempe',
    state: 'AZ',
    zipCode: '78664',
    county: 'Williamson',
    distance: 20,
  },
  {
    city: 'Glendale',
    state: 'AZ',
    zipCode: '78613',
    county: 'Williamson',
    distance: 25,
  },
  {
    city: 'Gilbert',
    state: 'AZ',
    zipCode: '78626',
    county: 'Williamson',
    distance: 30,
  },
  {
    city: 'Scottsdale',
    state: 'AZ',
    zipCode: '78666',
    county: 'Hays',
    distance: 35,
  },
  { city: 'Mesa', state: 'AZ', zipCode: '78610', county: 'Hays', distance: 40 },
]
